spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:h2_db
    username: root
    password: 123456
    schema: classpath:db/schema.sql
  h2:
    console:
      path: /h2
      enabled: true

mybatis:
  type-aliases-package: demo.microservice.entity
  configuration:
    map-underscore-to-camel-case: true
